### ISSUE TITLE
scanning multiple ports async callback is broken

### ISSUE THREAD

**Issue by tobsn** [baalexander/node-portscanner#33] opened 2015-08-05 15:33 UTC
portscanner/lib/portscanner.js:141
      callback(error, port)
      ^
TypeError: undefined is not a function

**Comment by sholladay** [comment] 2015-09-30 14:09
It looks like PR #28 made the (incorrect) assumption that JavaScript has method overloading. It should be fixed to detect array-like input with a simple `typeof foo === 'object' && foo.length` check.

**Comment by sholladay** [comment] 2015-09-30 14:12
FWIW, I expected that to be dealt with during a code review, before getting merged.

**Comment by trishayy** [comment] 2016-04-13 22:55
Still getting this error...

**Comment by sholladay** [comment] 2016-04-14 01:47
This should not be affecting the latest release on npm, `1.0.0`, as that came out before the above mentioned PR. The fix should be pretty easy, but its best to avoid installing from GitHub for now. :)

**Comment by trishayy** [comment] 2016-04-14 14:29
I did install via npm, and am using version 1.0.0... it seems to also be using version 0.1.15 of async? Not sure if that could be causing the problem. I've attached a screen shot of my node module versions, along with the error I'm getting.

npm module version #s:

![screen shot 2016-04-14 at 9 26 50 am](https://cloud.githubusercontent.com/assets/11196500/14531483/1a15ea88-0223-11e6-985a-3b0106c36309.png)



seems to be the same error as posted earlier:

![screen shot 2016-04-14 at 9 27 34 am](https://cloud.githubusercontent.com/assets/11196500/14531497/2e1b6724-0223-11e6-9c24-ce585eecb46a.png)


Thank you for your quick response, any help is greatly appreciated =)

**Comment by sholladay** [comment] 2016-04-14 16:16
This looks like a different problem. Could you post a [gist](https://gist.github.com/) with some code that I can run to reproduce the problem, so I can double check? Based on that error message, I am guessing that you aren't passing `portscanner` the number of arguments it is expecting (or in the right positions).

**Comment by laggingreflex** [comment] 2016-11-19 20:49
#28 has been reverted in the latest version, if that was indeed causing it, it should be fixed now. There have also been a few improvement in handling multiple signature arguments parsing. Released a new minor version 1.1.0, please check it out and let me know.

**Closed** 2017-11-29 19:51 UTC
